data_transformation:
  split_size: 0.2
  val_size: 0.2

HYPERPARAMETERS:
  early_stopping: [10]
  tuning_iterations: [100]
  num_epochs: [30, 50, 100]
  batch_size: [32, 128, 64]
  learning_rate: [0.1, 0.05, 0.01, 0.001]
  weight_decay: [0.0001, 0.00001, 0.001]
  sgd_momentum: [0.9, 0.8, 0.5]
  scheduler_gamma: [0.995, 0.9, 0.8, 0.5, 1]
  pos_weight : [1.0, 1.75, 3.5, 7.0, 14.0, 28.0]
  model_embedding_size: [8, 16, 32, 64, 128]
  model_attention_heads: [1, 2, 3, 4]
  model_layers: [3, 4, 5, 6]
  model_dropout_rate: [0.2, 0.5, 0.9]
  model_top_k_ratio: [0.2, 0.5, 0.8, 0.9]
  model_top_k_every_n: [1, 2, 3]
  model_dense_neurons: [16, 128, 64, 256, 32]

BEST_PARAMETERS:
  early_stopping: None
  tuning_iterations: None
  num_epochs: None
  batch_size: None
  learning_rate: None
  weight_decay: None
  sgd_momentum: None
  scheduler_gamma: None
  pos_weight: None
  model_embedding_size: None
  model_attention_heads: None
  model_layers: None
  model_dropout_rate: None
  model_top_k_ratio: None
  model_top_k_every_n: None
  model_dense_neurons: None
