artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/HIV.csv
  local_data_file: artifacts/data_ingestion/HIV.csv

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/HIV.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_csv: artifacts/data_ingestion/HIV.csv
  train_csv: artifacts/data_transformation/train.csv
  test_csv: artifacts/data_transformation/test.csv
  train_folder: artifacts/data_transformation/train
  test_folder: artifacts/data_transformation/test

model_trainer:
  root_dir: artifacts/model_trainer
  models: artifacts/model_trainer/models
  stats: artifacts/model_trainer/stats
  source_root: artifacts/data_ingestion
  processed_root: artifacts/data_transformation
  source_filename: HIV.csv
  processed_filename: [test, train, test.csv, train.csv]
  tuning: True

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_folder_path: artifacts/model_trainer/models/best_params
  source_root: artifacts/data_ingestion
  processed_root: artifacts/data_transformation
  source_filename: HIV.csv
  processed_filename: [test, train, test.csv, train.csv]
